package com.huggets.mynotes.sync

enum class Header(val value: Byte) {
    DATA_END(0x00),
    DATA_END_RECEIVED(0x01),

    DATES(0x02),
    DATES_COUNT(0x03),
    DATES_BUFFER_RECEIVED(0x04),

    NEEDED_NOTES(0x05),
    NEEDED_NOTES_COUNT(0x06),
    NEEDED_NOTES_BUFFER_RECEIVED(0x07),

    REQUESTED_NOTES(0x08),
    REQUESTED_NOTES_COUNT(0x09),
    REQUESTED_NOTES_BUFFER_RECEIVED(0x0A),
    REQUESTED_NOTES_BUFFER_END(0x0B),
    REQUESTED_NOTES_TITLE_LENGTH(0x0C),
    REQUESTED_NOTES_CONTENT_LENGTH(0x0D),
    REQUESTED_NOTES_CREATION_DATE(0x0E),
    REQUESTED_NOTES_LAST_MODIFICATION_DATE(0x0F),

    ASSOCIATIONS(0x10),
    ASSOCIATIONS_COUNT(0x11),
    ASSOCIATIONS_BUFFER_RECEIVED(0x12)
}